import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable, catchError, map, throwError } from 'rxjs';

export type Category = 'Electronics' | 'Furniture' | 'Clothing' | 'Tools' | 'Miscellaneous';
export type StockStatus = 'In Stock' | 'Low Stock' | 'Out of Stock';

// Backend database field names (snake_case)
export interface Item {
  item_id: number;          // Item ID (auto-incrementing)
  item_name: string;        // Item Name (required, unique)
  category: Category;       // Enum: Electronics, Furniture, Clothing, Tools, Miscellaneous
  quantity: number;         // Quantity (required)
  price: number;            // Price (required)
  supplier_name: string;    // Supplier Name (required)
  stock_status: StockStatus;// Enum: In Stock, Low Stock, Out of Stock
  featured_item: number;    // Featured Item (default: 0)
  special_note?: string;     // Special Note (optional)
}

@Injectable({
  providedIn: 'root'
})
export class InventoryService {
  private readonly API_URL = 'https://prog2005.it.scu.edu.au/ArtGalley';

  // No-cache headers to prevent 304 stale responses
  private noCacheHeaders = new HttpHeaders({
    'Cache-Control': 'no-cache, no-store, must-revalidate',
    'Pragma': 'no-cache'
  });

  constructor(private http: HttpClient) { }

  // GET all items
  getAllItems(): Observable<Item[]> {
    return this.http.get<Item[]>(this.API_URL + '/', { headers: this.noCacheHeaders })
      .pipe(map((items: any[]) => (items || []).map(item => this.normalizeItem(item))))
      .pipe(catchError(this.handleError));
  }

  // GET item by name (API may return array or single object)
  getItemByName(name: string): Observable<Item> {
    return this.http.get<any>(`${this.API_URL}/${encodeURIComponent(name)}`, { headers: this.noCacheHeaders })
      .pipe(map((res: any) => {
        let raw: any;
        if (Array.isArray(res)) {
          if (res.length === 0) {
            throw new Error('Item not found');
          }
          raw = res[0];
        } else {
          raw = res;
        }
        return this.normalizeItem(raw);
      }))
      .pipe(catchError(this.handleError));
  }

  private normalizeItem(raw: any): Item {
    return {
      item_id: Number(raw?.item_id ?? raw?.id ?? 0),
      item_name: String(raw?.item_name ?? raw?.name ?? ''),
      category: this.normalizeCategory(raw?.category),
      quantity: Number(raw?.quantity ?? 0),
      price: Number(raw?.price ?? 0),
      supplier_name: String(raw?.supplier_name ?? raw?.supplierName ?? ''),
      stock_status: this.normalizeStockStatus(raw?.stock_status ?? raw?.stockStatus),
      featured_item: Number(raw?.featured_item ?? raw?.featuredItem ?? 0),
      special_note: raw?.special_note ?? raw?.specialNote ?? ''
    };
  }

  // Normalize stock status to match enum exactly (API may return "In stock" instead of "In Stock")
  private normalizeStockStatus(val: string | undefined): StockStatus {
    if (!val) return 'In Stock';
    const lower = val.toLowerCase().trim();
    if (lower === 'in stock') return 'In Stock';
    if (lower === 'low stock') return 'Low Stock';
    if (lower === 'out of stock') return 'Out of Stock';
    return 'In Stock';
  }

  // Normalize category to match enum exactly
  private normalizeCategory(val: string | undefined): Category {
    if (!val) return 'Miscellaneous';
    const lower = val.toLowerCase().trim();
    if (lower === 'electronics') return 'Electronics';
    if (lower === 'furniture') return 'Furniture';
    if (lower === 'clothing') return 'Clothing';
    if (lower === 'tools') return 'Tools';
    return 'Miscellaneous';
  }

  // POST create new item (exclude item_id, auto-generated by server)
  createItem(item: Item): Observable<any> {
    const body = {
      item_name: item.item_name,
      category: item.category,
      quantity: item.quantity,
      price: item.price,
      supplier_name: item.supplier_name,
      stock_status: item.stock_status,
      featured_item: item.featured_item,
      special_note: item.special_note || ''
    };
    return this.http.post(this.API_URL + '/', body)
      .pipe(catchError(this.handleError));
  }

  // PUT update item by name (exclude item_id, send only editable fields)
  updateItem(name: string, item: Item): Observable<any> {
    const body = {
      item_name: item.item_name,
      category: item.category,
      quantity: item.quantity,
      price: item.price,
      supplier_name: item.supplier_name,
      stock_status: item.stock_status,
      featured_item: item.featured_item,
      special_note: item.special_note || ''
    };
    const url = `${this.API_URL}/${encodeURIComponent(name)}`;
    console.log('=== PUT Request ===');
    console.log('URL:', url);
    console.log('Body:', JSON.stringify(body, null, 2));
    return this.http.put(url, body)
      .pipe(
        map((res: any) => {
          console.log('=== PUT Response ===', res);
          return res;
        }),
        catchError(this.handleError)
      );
  }

  // DELETE item by name
  deleteItem(name: string): Observable<any> {
    return this.http.delete(`${this.API_URL}/${encodeURIComponent(name)}`)
      .pipe(catchError(this.handleError));
  }

  // Search items locally after fetching all
  searchItems(items: Item[], query: string): Item[] {
    if (!query.trim()) return items;
    const lowerQuery = query.toLowerCase();
    return items.filter(item =>
      item.item_name.toLowerCase().includes(lowerQuery) ||
      item.category.toLowerCase().includes(lowerQuery) ||
      item.supplier_name.toLowerCase().includes(lowerQuery)
    );
  }

  // Get featured items (featured_item > 0)
  getFeaturedItems(items: Item[]): Item[] {
    return items.filter(item => item.featured_item > 0);
  }

  private handleError(error: any) {
    let message = 'An unexpected error occurred';
    if (error.error?.message) {
      message = error.error.message;
    } else if (error.message) {
      message = error.message;
    } else if (error.status === 0) {
      message = 'Unable to connect to server. Please check your internet connection.';
    } else if (error.status === 403) {
      message = 'This operation is forbidden. The item "Laptop" cannot be deleted.';
    } else if (error.status === 404) {
      message = 'Item not found.';
    } else if (error.status === 409) {
      message = 'An item with this name already exists.';
    }
    return throwError(() => new Error(message));
  }
}
